// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const committedSequences = `-- name: CommittedSequences :many
SELECT id, event_seq FROM organization WHERE id = ANY($1::uuid[])
`

type CommittedSequencesRow struct {
	ID       pgtype.UUID
	EventSeq int64
}

func (q *Queries) CommittedSequences(ctx context.Context, organizationIds []pgtype.UUID) ([]CommittedSequencesRow, error) {
	rows, err := q.db.Query(ctx, committedSequences, organizationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommittedSequencesRow
	for rows.Next() {
		var i CommittedSequencesRow
		if err := rows.Scan(&i.ID, &i.EventSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventBounds = `-- name: EventBounds :one
SELECT event_log_boundary_seq, event_seq FROM organization WHERE id = $1
`

type EventBoundsRow struct {
	EventLogBoundarySeq int64
	EventSeq            int64
}

// realtime's reader reads org's cursor bounds through this, in its snapshot.
func (q *Queries) EventBounds(ctx context.Context, id pgtype.UUID) (EventBoundsRow, error) {
	row := q.db.QueryRow(ctx, eventBounds, id)
	var i EventBoundsRow
	err := row.Scan(&i.EventLogBoundarySeq, &i.EventSeq)
	return i, err
}

const getEventSeq = `-- name: GetEventSeq :one
SELECT event_seq FROM organization WHERE id = $1
`

// The latest page's cursor, read in the page's snapshot.
func (q *Queries) GetEventSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEventSeq, id)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}

const lockEventRetentionOrganization = `-- name: LockEventRetentionOrganization :exec
SELECT id FROM organization WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockEventRetentionOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockEventRetentionOrganization, id)
	return err
}

const nextEventSeq = `-- name: NextEventSeq :one
UPDATE organization SET event_seq = event_seq + 1 WHERE id = $1 RETURNING event_seq
`

// Posting and branching take this first: the row lock makes sequence order
// commit order (decision 5).
func (q *Queries) NextEventSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextEventSeq, id)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}

const raiseEventLogBoundary = `-- name: RaiseEventLogBoundary :exec
UPDATE organization SET event_log_boundary_seq = greatest(event_log_boundary_seq, $1::bigint)
WHERE id = $2
`

type RaiseEventLogBoundaryParams struct {
	Through        int64
	OrganizationID pgtype.UUID
}

// greatest: the boundary never goes down (realtime.RetentionBoundary).
func (q *Queries) RaiseEventLogBoundary(ctx context.Context, arg RaiseEventLogBoundaryParams) error {
	_, err := q.db.Exec(ctx, raiseEventLogBoundary, arg.Through, arg.OrganizationID)
	return err
}
