//go:build lintfixture

// Code generated by lint fixture. DO NOT EDIT.

package lintfixture

import "strings"

// IgnoredGeneratedResult proves generated templates still run staticcheck.
func IgnoredGeneratedResult(value string) { strings.TrimSpace(value) }
