version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/tools"
      - "/tools/tbls"
    schedule:
      interval: weekly
    groups:
      templ:
        patterns:
          - "github.com/a-h/templ"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
