package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSummaryAndFreshness(t *testing.T) {
	root := t.TempDir()
	write := func(path, text string) {
		t.Helper()
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write(filepath.Join(root, "go.mod"), "module fixture\n\ngo 1.27.1\n")
	for _, name := range []string{"conversation", "identity", "org", "realtime", "unread"} {
		write(filepath.Join(root, "internal", name, "api.go"), "package "+name+"\n")
	}
	path := filepath.Join(root, "internal/identity/api.go")
	const source = `package identity
// Zed is a constant. Another sentence.
const Zed = 7
// Errors are variables. More detail.
var (ErrExample error; ErrOther error)
// Item is public. Another sentence.
type Item[T any] struct {
 // Value is visible. More detail.
 Value T
 private int
}
// Open is callable. Another sentence.
func (*Item[T]) Open() {}
func (*Item[T]) privateMethod() {}
// ExtendedReader also closes.
type ExtendedReader interface {
 Reader
 // Close releases resources.
 Close() error
}
// Reader reads. More detail.
type Reader interface {
 error
 // Read gets data. More detail.
 Read() string
 privateMethod()
}
type hidden struct { Leaked string }
func (hidden) LeakedMethod() {}
// New builds an item. More detail.
func New() *Item[string] { return nil }
`
	write(path, source)
	if err := run(root, false); err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(root, "docs/api/identity.txt")
	before, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	const want = "# Generated by make api; do not edit.\npackage fixture/internal/identity\n\nvar ErrExample error // Errors are variables.\nvar ErrOther error // Errors are variables.\ntype ExtendedReader interface [embeds Reader] // ExtendedReader also closes.\n  func (ExtendedReader).Close() error // Close releases resources.\n  func (error).Error() string\n  func (Reader).Read() string // Read gets data.\ntype Item[T any] struct // Item is public.\n  func (*Item[T]).Open() // Open is callable.\n  field Value T // Value is visible.\nfunc New() *Item[string] // New builds an item.\ntype Reader interface [embeds error] // Reader reads.\n  func (error).Error() string\n  func (Reader).Read() string // Read gets data.\nconst Zed untyped int = 7 // Zed is a constant.\n"
	if string(before) != want {
		t.Fatalf("summary:\n%s\nwant:\n%s", before, want)
	}
	if err := run(root, false); err != nil {
		t.Fatal(err)
	}
	if after, err := os.ReadFile(file); err != nil || string(after) != string(before) {
		t.Fatalf("nondeterministic generation: %v", err)
	}
	if err := run(root, true); err != nil {
		t.Fatal(err)
	}
	for _, addition := range []string{"const Added = 1", "var Added error", "type Added int", "func Added() {}", "func (*Item[T]) Added() {}", "type Added struct { Field int }", "type Added interface { Method() }"} {
		t.Run(addition, func(t *testing.T) {
			write(path, source+addition+"\n")
			if err := run(root, true); err == nil || !strings.Contains(err.Error(), "stale") {
				t.Fatalf("freshness accepted exported addition: %v", err)
			}
			after, err := os.ReadFile(file)
			if err != nil || string(after) != string(before) {
				t.Fatalf("check rewrote summary: %v", err)
			}
		})
	}
	write(path, source)
	if err := os.Remove(file); err != nil {
		t.Fatal(err)
	}
	if err := run(root, true); err == nil {
		t.Fatal("check accepted missing summary")
	}
	if _, err := os.Stat(file); !os.IsNotExist(err) {
		t.Fatal("check created missing summary")
	}
	write(path, "package identity\nvar Broken = missing\n")
	if err := run(root, false); err == nil {
		t.Fatal("generation accepted package errors")
	}
}
