// Command apicheck generates module-root API summaries; -check only compares.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	check := flag.Bool("check", false, "fail on stale summaries without writing")
	flag.Parse()
	if flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: apicheck [-check] <repository root>")
		os.Exit(2)
	}
	if err := run(flag.Arg(0), *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	patterns := []string{"./internal/conversation", "./internal/identity", "./internal/org", "./internal/realtime"}
	pkgs, err := packages.Load(&packages.Config{Dir: root, Mode: packages.LoadSyntax,
		Env: append(os.Environ(), "GOOS=linux", "GOARCH=amd64", "CGO_ENABLED=0", "GOFLAGS=")}, patterns...)
	if err != nil {
		return fmt.Errorf("loading API: %w", err)
	}
	if packages.PrintErrors(pkgs) > 0 || len(pkgs) != len(patterns) {
		return fmt.Errorf("loading API: expected four valid module roots")
	}
	slices.SortFunc(pkgs, func(a, b *packages.Package) int { return strings.Compare(a.PkgPath, b.PkgPath) })
	for _, p := range pkgs {
		path := filepath.Join(root, "docs/api", p.Name+".txt")
		content := summary(p)
		if check {
			old, err := os.ReadFile(path)
			if err != nil || string(old) != content {
				return fmt.Errorf("%s is missing or stale: run make api", path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("creating API directory: %w", err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing API: %w", err)
		}
	}
	return nil
}

func summary(p *packages.Package) string {
	synopsis := (&doc.Package{}).Synopsis
	comments := map[token.Pos]string{}
	for _, f := range p.Syntax {
		ast.Inspect(f, func(n ast.Node) bool {
			var ids []*ast.Ident
			var c *ast.CommentGroup
			switch n := n.(type) {
			case *ast.GenDecl:
				for _, spec := range n.Specs {
					comments[spec.Pos()] = synopsis(n.Doc.Text())
				}
			case *ast.TypeSpec:
				ids, c = []*ast.Ident{n.Name}, n.Doc
			case *ast.ValueSpec:
				ids, c = n.Names, n.Doc
			case *ast.FuncDecl:
				ids, c = []*ast.Ident{n.Name}, n.Doc
			case *ast.Field:
				comments[n.Pos()] = synopsis(n.Doc.Text())
				ids, c = n.Names, n.Doc
			}
			for _, id := range ids {
				text := comments[n.Pos()]
				if c != nil {
					text = synopsis(c.Text())
				}
				comments[id.Pos()] = text
			}
			return true
		})
	}
	q := types.RelativeTo(p.Types)
	var out strings.Builder
	fmt.Fprintf(&out, "# Generated by make api; do not edit.\npackage %s\n\n", p.PkgPath)
	write := func(signature string, o types.Object) {
		fmt.Fprintf(&out, "%s", signature)
		if text := comments[o.Pos()]; text != "" {
			fmt.Fprintf(&out, " // %s", text)
		}
		out.WriteByte('\n')
	}
	names := p.Types.Scope().Names()
	slices.Sort(names)
	for _, name := range names {
		o := p.Types.Scope().Lookup(name)
		if !o.Exported() {
			continue
		}
		signature := types.ObjectString(o, q)
		var members []types.Object
		if t, ok := o.(*types.TypeName); ok && !t.IsAlias() {
			named := t.Type().(*types.Named)
			switch u := named.Underlying().(type) {
			case *types.Struct:
				signature = strings.TrimSuffix(signature, types.TypeString(u, q)) + "struct"
				for i := 0; i < u.NumFields(); i++ {
					members = append(members, u.Field(i))
				}
			case *types.Interface:
				signature = strings.TrimSuffix(signature, types.TypeString(u, q)) + "interface"
				for i := 0; i < u.NumExplicitMethods(); i++ {
					members = append(members, u.ExplicitMethod(i))
				}
				for i := 0; i < u.NumEmbeddeds(); i++ {
					signature += " [embeds " + types.TypeString(u.EmbeddedType(i), q) + "]"
				}
			}
			for i := 0; i < named.NumMethods(); i++ {
				members = append(members, named.Method(i))
			}
		}
		if c, ok := o.(*types.Const); ok {
			signature += " = " + c.Val().ExactString()
		}
		write(signature, o)
		slices.SortFunc(members, func(a, b types.Object) int { return strings.Compare(a.Name(), b.Name()) })
		for _, m := range members {
			if m.Exported() {
				write("  "+types.ObjectString(m, q), m)
			}
		}
	}
	return out.String()
}
