// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ranges.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRangeNeighbours = `-- name: DeleteRangeNeighbours :many
DELETE FROM read_range
WHERE organization_id = $1 AND channel_id = $2 AND member_id = $3
  AND $4::bigint <= lo AND lo <= $5::bigint
  AND $6::bigint <= hi
RETURNING lo, hi
`

type DeleteRangeNeighboursParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	LowerLo        int64
	Hi             int64
	Lo             int64
}

type DeleteRangeNeighboursRow struct {
	Lo int64
	Hi int64
}

func (q *Queries) DeleteRangeNeighbours(ctx context.Context, arg DeleteRangeNeighboursParams) ([]DeleteRangeNeighboursRow, error) {
	rows, err := q.db.Query(ctx, deleteRangeNeighbours,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.LowerLo,
		arg.Hi,
		arg.Lo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteRangeNeighboursRow
	for rows.Next() {
		var i DeleteRangeNeighboursRow
		if err := rows.Scan(&i.Lo, &i.Hi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannelRead = `-- name: InsertChannelRead :exec
INSERT INTO channel_read (organization_id, channel_id, member_id) VALUES ($1, $2, $3)
`

type InsertChannelReadParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
}

func (q *Queries) InsertChannelRead(ctx context.Context, arg InsertChannelReadParams) error {
	_, err := q.db.Exec(ctx, insertChannelRead, arg.OrganizationID, arg.ChannelID, arg.MemberID)
	return err
}

const insertReadRange = `-- name: InsertReadRange :exec
INSERT INTO read_range (organization_id, channel_id, member_id, lo, hi) VALUES ($1, $2, $3, $4, $5)
`

type InsertReadRangeParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	Lo             int64
	Hi             int64
}

func (q *Queries) InsertReadRange(ctx context.Context, arg InsertReadRangeParams) error {
	_, err := q.db.Exec(ctx, insertReadRange,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.Lo,
		arg.Hi,
	)
	return err
}

const lockChannelRead = `-- name: LockChannelRead :one
SELECT channel_id FROM channel_read
WHERE organization_id = $1 AND channel_id = $2 AND member_id = $3
FOR UPDATE
`

type LockChannelReadParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
}

func (q *Queries) LockChannelRead(ctx context.Context, arg LockChannelReadParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockChannelRead, arg.OrganizationID, arg.ChannelID, arg.MemberID)
	var channel_id pgtype.UUID
	err := row.Scan(&channel_id)
	return channel_id, err
}

const rangePredecessor = `-- name: RangePredecessor :one
SELECT lo, hi FROM read_range
WHERE organization_id = $1 AND channel_id = $2 AND member_id = $3 AND lo <= $4
ORDER BY lo DESC LIMIT 1
`

type RangePredecessorParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	Lo             int64
}

type RangePredecessorRow struct {
	Lo int64
	Hi int64
}

func (q *Queries) RangePredecessor(ctx context.Context, arg RangePredecessorParams) (RangePredecessorRow, error) {
	row := q.db.QueryRow(ctx, rangePredecessor,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.Lo,
	)
	var i RangePredecessorRow
	err := row.Scan(&i.Lo, &i.Hi)
	return i, err
}
