// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchRangeNeighbours = `-- name: BatchRangeNeighbours :many
SELECT DISTINCT r.lo, r.hi FROM
unnest($1::bigint[]) WITH ORDINALITY AS a(lo, n)
JOIN unnest($2::bigint[]) WITH ORDINALITY AS b(hi, n) ON a.n = b.n
JOIN read_range r ON r.lo <= b.hi
WHERE r.organization_id = $3
  AND r.channel_id = $4 AND r.member_id = $5
  AND a.lo <= r.hi
  AND (SELECT p.lo FROM read_range p
       WHERE p.organization_id = $3
         AND p.channel_id = $4 AND p.member_id = $5
         AND p.lo <= a.lo ORDER BY p.lo DESC LIMIT 1) <= r.lo
`

type BatchRangeNeighboursParams struct {
	Los            []int64
	His            []int64
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
}

type BatchRangeNeighboursRow struct {
	Lo int64
	Hi int64
}

// Requires the prefix row (lo = 0) that Prepare creates under the channel lock:
// without a predecessor the subquery is NULL and the range matches nothing.
func (q *Queries) BatchRangeNeighbours(ctx context.Context, arg BatchRangeNeighboursParams) ([]BatchRangeNeighboursRow, error) {
	rows, err := q.db.Query(ctx, batchRangeNeighbours,
		arg.Los,
		arg.His,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchRangeNeighboursRow
	for rows.Next() {
		var i BatchRangeNeighboursRow
		if err := rows.Scan(&i.Lo, &i.Hi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBatchRanges = `-- name: DeleteBatchRanges :exec
DELETE FROM read_range
WHERE organization_id = $1 AND channel_id = $2 AND member_id = $3
  AND lo IN (SELECT value FROM unnest($4::bigint[]) AS a(value))
`

type DeleteBatchRangesParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	Los            []int64
}

func (q *Queries) DeleteBatchRanges(ctx context.Context, arg DeleteBatchRangesParams) error {
	_, err := q.db.Exec(ctx, deleteBatchRanges,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.Los,
	)
	return err
}

const insertBatchRanges = `-- name: InsertBatchRanges :exec
WITH bounds AS (
  SELECT a.lo, b.hi FROM
  unnest($4::bigint[]) WITH ORDINALITY AS a(lo, n)
  JOIN unnest($5::bigint[]) WITH ORDINALITY AS b(hi, n) ON a.n = b.n
)
INSERT INTO read_range (organization_id, channel_id, member_id, lo, hi)
SELECT $1, $2, $3, lo, hi FROM bounds
`

type InsertBatchRangesParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	Los            []int64
	His            []int64
}

func (q *Queries) InsertBatchRanges(ctx context.Context, arg InsertBatchRangesParams) error {
	_, err := q.db.Exec(ctx, insertBatchRanges,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.Los,
		arg.His,
	)
	return err
}

const insertTopicReadFloor = `-- name: InsertTopicReadFloor :exec
INSERT INTO topic_read_floor (organization_id, channel_id, member_id, topic_id, floor_seq)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTopicReadFloorParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	TopicID        pgtype.UUID
	FloorSeq       int64
}

func (q *Queries) InsertTopicReadFloor(ctx context.Context, arg InsertTopicReadFloorParams) error {
	_, err := q.db.Exec(ctx, insertTopicReadFloor,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.TopicID,
		arg.FloorSeq,
	)
	return err
}

const raiseTopicReadFloor = `-- name: RaiseTopicReadFloor :exec
UPDATE topic_read_floor SET floor_seq = $5
WHERE organization_id = $1 AND channel_id = $2 AND member_id = $3 AND topic_id = $4
  AND floor_seq < $5
`

type RaiseTopicReadFloorParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	TopicID        pgtype.UUID
	FloorSeq       int64
}

func (q *Queries) RaiseTopicReadFloor(ctx context.Context, arg RaiseTopicReadFloorParams) error {
	_, err := q.db.Exec(ctx, raiseTopicReadFloor,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.TopicID,
		arg.FloorSeq,
	)
	return err
}

const readTopicState = `-- name: ReadTopicState :many
WITH requested AS (
  SELECT t.id, t.n
  FROM unnest($1::uuid[]) WITH ORDINALITY AS t(id, n)
)
SELECT 0::bigint AS topic_n, r.lo AS value, r.hi
FROM read_range r
WHERE r.organization_id = $2
  AND r.channel_id = $3 AND r.member_id = $4
UNION ALL
SELECT t.n, f.floor_seq, 0::bigint
FROM requested t
JOIN topic_read_floor f ON true
WHERE f.organization_id = $2
  AND f.channel_id = $3 AND f.member_id = $4
  AND f.topic_id = t.id
ORDER BY topic_n, value
`

type ReadTopicStateParams struct {
	TopicIds       []pgtype.UUID
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
}

type ReadTopicStateRow struct {
	TopicN int64
	Value  int64
	Hi     int64
}

// Ranges are separate from floors, so each range is returned only once.
func (q *Queries) ReadTopicState(ctx context.Context, arg ReadTopicStateParams) ([]ReadTopicStateRow, error) {
	rows, err := q.db.Query(ctx, readTopicState,
		arg.TopicIds,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadTopicStateRow
	for rows.Next() {
		var i ReadTopicStateRow
		if err := rows.Scan(&i.TopicN, &i.Value, &i.Hi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topicReadFloor = `-- name: TopicReadFloor :one
SELECT floor_seq FROM topic_read_floor
WHERE organization_id = $1 AND channel_id = $2 AND member_id = $3 AND topic_id = $4
`

type TopicReadFloorParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	TopicID        pgtype.UUID
}

func (q *Queries) TopicReadFloor(ctx context.Context, arg TopicReadFloorParams) (int64, error) {
	row := q.db.QueryRow(ctx, topicReadFloor,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.TopicID,
	)
	var floor_seq int64
	err := row.Scan(&floor_seq)
	return floor_seq, err
}

const topicReadRanges = `-- name: TopicReadRanges :many
SELECT lo, hi FROM read_range
WHERE organization_id = $1 AND channel_id = $2 AND member_id = $3
ORDER BY lo
`

type TopicReadRangesParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
}

type TopicReadRangesRow struct {
	Lo int64
	Hi int64
}

func (q *Queries) TopicReadRanges(ctx context.Context, arg TopicReadRangesParams) ([]TopicReadRangesRow, error) {
	rows, err := q.db.Query(ctx, topicReadRanges, arg.OrganizationID, arg.ChannelID, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopicReadRangesRow
	for rows.Next() {
		var i TopicReadRangesRow
		if err := rows.Scan(&i.Lo, &i.Hi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
