// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (email, display_name, password_hash) VALUES ($1, $2, $3) RETURNING id, email, display_name, password_hash, created_at
`

type CreateAccountParams struct {
	Email        string
	DisplayName  string
	PasswordHash string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, display_name, password_hash, created_at FROM account WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, display_name, password_hash, created_at FROM account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const lookupDisplayNames = `-- name: LookupDisplayNames :many
SELECT id, display_name FROM account WHERE id = ANY($1::uuid[])
`

type LookupDisplayNamesRow struct {
	ID          pgtype.UUID
	DisplayName string
}

func (q *Queries) LookupDisplayNames(ctx context.Context, accountIds []pgtype.UUID) ([]LookupDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, lookupDisplayNames, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupDisplayNamesRow
	for rows.Next() {
		var i LookupDisplayNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
