// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const committedSequences = `-- name: CommittedSequences :many
SELECT id, event_seq FROM organization WHERE id = ANY($1::uuid[])
`

type CommittedSequencesRow struct {
	ID       pgtype.UUID
	EventSeq int64
}

func (q *Queries) CommittedSequences(ctx context.Context, organizationIds []pgtype.UUID) ([]CommittedSequencesRow, error) {
	rows, err := q.db.Query(ctx, committedSequences, organizationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommittedSequencesRow
	for rows.Next() {
		var i CommittedSequencesRow
		if err := rows.Scan(&i.ID, &i.EventSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsAfter = `-- name: EventsAfter :many
SELECT organization_id, seq, kind, audience_member_id, data
FROM event_log
WHERE organization_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3::bigint
`

type EventsAfterParams struct {
	OrganizationID pgtype.UUID
	AfterSeq       int64
	BatchLimit     int64
}

type EventsAfterRow struct {
	OrganizationID   pgtype.UUID
	Seq              int64
	Kind             string
	AudienceMemberID pgtype.UUID
	Data             []byte
}

func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]EventsAfterRow, error) {
	rows, err := q.db.Query(ctx, eventsAfter, arg.OrganizationID, arg.AfterSeq, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsAfterRow
	for rows.Next() {
		var i EventsAfterRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Seq,
			&i.Kind,
			&i.AudienceMemberID,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMemberEvent = `-- name: InsertMemberEvent :exec
INSERT INTO event_log (organization_id, seq, kind, audience_member_id, data)
VALUES ($1, $2, $3, NULL, jsonb_build_object('member_id', $4::uuid))
`

type InsertMemberEventParams struct {
	OrganizationID pgtype.UUID
	Seq            int64
	Kind           string
	MemberID       pgtype.UUID
}

func (q *Queries) InsertMemberEvent(ctx context.Context, arg InsertMemberEventParams) error {
	_, err := q.db.Exec(ctx, insertMemberEvent,
		arg.OrganizationID,
		arg.Seq,
		arg.Kind,
		arg.MemberID,
	)
	return err
}

const insertMessageEvent = `-- name: InsertMessageEvent :exec
INSERT INTO event_log (organization_id, seq, kind, audience_member_id, data)
VALUES ($1, $2, $3, NULL, jsonb_build_object('channel_id', $4::uuid, 'message_id', $5::uuid))
`

type InsertMessageEventParams struct {
	OrganizationID pgtype.UUID
	Seq            int64
	Kind           string
	ChannelID      pgtype.UUID
	MessageID      pgtype.UUID
}

func (q *Queries) InsertMessageEvent(ctx context.Context, arg InsertMessageEventParams) error {
	_, err := q.db.Exec(ctx, insertMessageEvent,
		arg.OrganizationID,
		arg.Seq,
		arg.Kind,
		arg.ChannelID,
		arg.MessageID,
	)
	return err
}
