// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMemberEvent = `-- name: InsertMemberEvent :exec
INSERT INTO event_log (organization_id, seq, kind, audience_member_id, data)
VALUES ($1, $2, $3, NULL, jsonb_build_object('member_id', $4::uuid))
`

type InsertMemberEventParams struct {
	OrganizationID pgtype.UUID
	Seq            int64
	Kind           string
	MemberID       pgtype.UUID
}

func (q *Queries) InsertMemberEvent(ctx context.Context, arg InsertMemberEventParams) error {
	_, err := q.db.Exec(ctx, insertMemberEvent,
		arg.OrganizationID,
		arg.Seq,
		arg.Kind,
		arg.MemberID,
	)
	return err
}

const insertMessageEvent = `-- name: InsertMessageEvent :exec
INSERT INTO event_log (organization_id, seq, kind, audience_member_id, data)
VALUES ($1, $2, $3, NULL, jsonb_build_object('channel_id', $4::uuid, 'message_id', $5::uuid))
`

type InsertMessageEventParams struct {
	OrganizationID pgtype.UUID
	Seq            int64
	Kind           string
	ChannelID      pgtype.UUID
	MessageID      pgtype.UUID
}

func (q *Queries) InsertMessageEvent(ctx context.Context, arg InsertMessageEventParams) error {
	_, err := q.db.Exec(ctx, insertMessageEvent,
		arg.OrganizationID,
		arg.Seq,
		arg.Kind,
		arg.ChannelID,
		arg.MessageID,
	)
	return err
}
