// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member (organization_id, account_id, role, joined_event_seq, handle)
VALUES ($1, $2, $3, $4, $5) RETURNING id, organization_id, account_id, role, joined_event_seq, created_at, handle
`

type CreateMemberParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
	JoinedEventSeq int64
	Handle         string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.OrganizationID,
		arg.AccountID,
		arg.Role,
		arg.JoinedEventSeq,
		arg.Handle,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.JoinedEventSeq,
		&i.CreatedAt,
		&i.Handle,
	)
	return i, err
}

const getMemberByOrganizationAndAccount = `-- name: GetMemberByOrganizationAndAccount :one
SELECT id, organization_id, account_id, role, joined_event_seq, created_at, handle FROM member WHERE organization_id = $1 AND account_id = $2
`

type GetMemberByOrganizationAndAccountParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) GetMemberByOrganizationAndAccount(ctx context.Context, arg GetMemberByOrganizationAndAccountParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByOrganizationAndAccount, arg.OrganizationID, arg.AccountID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.JoinedEventSeq,
		&i.CreatedAt,
		&i.Handle,
	)
	return i, err
}
