// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member (organization_id, account_id, role, joined_event_seq, handle)
VALUES ($1, $2, $3, $4, $5) RETURNING id, organization_id, account_id, role, joined_event_seq, created_at, handle
`

type CreateMemberParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
	JoinedEventSeq int64
	Handle         string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.OrganizationID,
		arg.AccountID,
		arg.Role,
		arg.JoinedEventSeq,
		arg.Handle,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.JoinedEventSeq,
		&i.CreatedAt,
		&i.Handle,
	)
	return i, err
}

const getHomeSlug = `-- name: GetHomeSlug :one
SELECT o.slug
FROM setup s
JOIN organization o ON o.id = s.organization_id
JOIN member m ON m.organization_id = o.id
WHERE m.account_id = $1
`

func (q *Queries) GetHomeSlug(ctx context.Context, accountID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getHomeSlug, accountID)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getMemberByOrganizationAndAccount = `-- name: GetMemberByOrganizationAndAccount :one
SELECT id, organization_id, account_id, role, joined_event_seq, created_at, handle FROM member WHERE organization_id = $1 AND account_id = $2
`

type GetMemberByOrganizationAndAccountParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) GetMemberByOrganizationAndAccount(ctx context.Context, arg GetMemberByOrganizationAndAccountParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByOrganizationAndAccount, arg.OrganizationID, arg.AccountID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.JoinedEventSeq,
		&i.CreatedAt,
		&i.Handle,
	)
	return i, err
}

const getMembershipBySlug = `-- name: GetMembershipBySlug :one
SELECT o.id AS organization_id, o.slug, o.name, m.id AS member_id, m.role, m.handle
FROM organization o
JOIN member m ON m.organization_id = o.id
WHERE o.slug = $1 AND m.account_id = $2
`

type GetMembershipBySlugParams struct {
	Slug      string
	AccountID pgtype.UUID
}

type GetMembershipBySlugRow struct {
	OrganizationID pgtype.UUID
	Slug           string
	Name           string
	MemberID       pgtype.UUID
	Role           string
	Handle         string
}

func (q *Queries) GetMembershipBySlug(ctx context.Context, arg GetMembershipBySlugParams) (GetMembershipBySlugRow, error) {
	row := q.db.QueryRow(ctx, getMembershipBySlug, arg.Slug, arg.AccountID)
	var i GetMembershipBySlugRow
	err := row.Scan(
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.MemberID,
		&i.Role,
		&i.Handle,
	)
	return i, err
}
