// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO message (organization_id, channel_id, member_id, body, event_seq)
VALUES ($1, $2, $3, $4, $5) RETURNING id, organization_id, channel_id, member_id, body, event_seq, created_at
`

type InsertMessageParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	Body           string
	EventSeq       int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.OrganizationID,
		arg.ChannelID,
		arg.MemberID,
		arg.Body,
		arg.EventSeq,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.MemberID,
		&i.Body,
		&i.EventSeq,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, organization_id, channel_id, member_id, body, event_seq, created_at FROM message
WHERE organization_id = $1 AND channel_id = $2
  AND ($3::bigint IS NULL OR event_seq < $3::bigint)
ORDER BY event_seq DESC
LIMIT $4
`

type ListMessagesBeforeParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	BeforeEventSeq pgtype.Int8
	Limit          int32
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore,
		arg.OrganizationID,
		arg.ChannelID,
		arg.BeforeEventSeq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelID,
			&i.MemberID,
			&i.Body,
			&i.EventSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
