// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Topic struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	Name           pgtype.Text
	IsDefault      bool
	CreatedAt      pgtype.Timestamptz
}
