// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Channel struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	Name                  string
	IsDefault             bool
	CreatedAt             pgtype.Timestamptz
	DefaultTopicID        pgtype.UUID
	DefaultTopicIsDefault bool
}

type Member struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
	JoinedEventSeq int64
	CreatedAt      pgtype.Timestamptz
	Handle         string
}

type Message struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MemberID       pgtype.UUID
	Body           string
	EventSeq       int64
	CreatedAt      pgtype.Timestamptz
	TopicID        pgtype.UUID
}

type Organization struct {
	ID                  pgtype.UUID
	Slug                string
	Name                string
	EventSeq            int64
	CreatedAt           pgtype.Timestamptz
	EventLogBoundarySeq int64
}

type Topic struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	Name           pgtype.Text
	IsDefault      bool
	CreatedAt      pgtype.Timestamptz
}
