// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	EventSeq  int64
	CreatedAt pgtype.Timestamptz
}
