// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventSeq = `-- name: GetEventSeq :one
SELECT event_seq FROM organization WHERE id = $1
`

// A copy of org's GetEventSeq (db/queries/org/), until 3.12.
func (q *Queries) GetEventSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEventSeq, id)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}

const nextEventSeq = `-- name: NextEventSeq :one
UPDATE organization SET event_seq = event_seq + 1 WHERE id = $1 RETURNING event_seq
`

// Setup and sign-up's copy of org's NextEventSeq (db/queries/org/), until 3.12.
func (q *Queries) NextEventSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextEventSeq, id)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}
