// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventSeq = `-- name: GetEventSeq :one
SELECT event_seq FROM organization WHERE id = $1
`

func (q *Queries) GetEventSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEventSeq, id)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, event_seq, created_at, event_log_boundary_seq FROM organization WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EventSeq,
		&i.CreatedAt,
		&i.EventLogBoundarySeq,
	)
	return i, err
}

const nextEventSeq = `-- name: NextEventSeq :one
UPDATE organization SET event_seq = event_seq + 1 WHERE id = $1 RETURNING event_seq
`

func (q *Queries) NextEventSeq(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextEventSeq, id)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}
