// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package sqlcgen

import (
	"context"
)

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, event_seq, created_at FROM organization WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EventSeq,
		&i.CreatedAt,
	)
	return i, err
}
