// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (token_hash, account_id, expires_at) VALUES ($1, $2, $3) RETURNING id, token_hash, account_id, created_at, expires_at
`

type CreateSessionParams struct {
	TokenHash []byte
	AccountID pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.AccountID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM session WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT session.id, session.token_hash, session.account_id, session.created_at, session.expires_at, account.id, account.email, account.display_name, account.password_hash, account.created_at
FROM session JOIN account ON account.id = session.account_id
WHERE session.token_hash = $1 AND session.expires_at > $2
`

type GetSessionByTokenHashParams struct {
	TokenHash []byte
	Now       pgtype.Timestamptz
}

type GetSessionByTokenHashRow struct {
	Session Session
	Account Account
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash, arg.Now)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.TokenHash,
		&i.Session.AccountID,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.Account.ID,
		&i.Account.Email,
		&i.Account.DisplayName,
		&i.Account.PasswordHash,
		&i.Account.CreatedAt,
	)
	return i, err
}
