// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSetup = `-- name: CompleteSetup :exec
INSERT INTO setup (id, organization_id) VALUES (true, $1)
`

// A copy of org's CompleteSetup (db/queries/org/), until 3.12.
func (q *Queries) CompleteSetup(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeSetup, organizationID)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (name, slug) VALUES ($1, $2) RETURNING id, slug, name, event_seq, created_at, event_log_boundary_seq
`

type CreateOrganizationParams struct {
	Name string
	Slug string
}

// A copy of org's CreateOrganization (db/queries/org/), until 3.12.
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.EventSeq,
		&i.CreatedAt,
		&i.EventLogBoundarySeq,
	)
	return i, err
}

const setupOpen = `-- name: SetupOpen :one
SELECT NOT EXISTS (SELECT 1 FROM setup)
`

// A copy of org's SetupOpen (db/queries/org/), until 3.12.
func (q *Queries) SetupOpen(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, setupOpen)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}
