// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topic (organization_id, channel_id, name, is_default)
VALUES ($1, $2, $3, $4) RETURNING id, organization_id, channel_id, name, is_default, created_at
`

type CreateTopicParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	Name           pgtype.Text
	IsDefault      bool
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.OrganizationID,
		arg.ChannelID,
		arg.Name,
		arg.IsDefault,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultTopic = `-- name: GetDefaultTopic :one
SELECT id, organization_id, channel_id, name, is_default, created_at FROM topic WHERE organization_id = $1 AND channel_id = $2 AND is_default
`

type GetDefaultTopicParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
}

func (q *Queries) GetDefaultTopic(ctx context.Context, arg GetDefaultTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getDefaultTopic, arg.OrganizationID, arg.ChannelID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
SELECT id, organization_id, channel_id, name, is_default, created_at FROM topic WHERE organization_id = $1 AND channel_id = $2 AND id = $3
`

type GetTopicParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) GetTopic(ctx context.Context, arg GetTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, arg.OrganizationID, arg.ChannelID, arg.ID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT id, organization_id, channel_id, name, is_default, created_at FROM topic
WHERE organization_id = $1 AND channel_id = $2
ORDER BY is_default DESC, lower(name), id
LIMIT $3
`

type ListTopicsParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	Limit          int32
}

func (q *Queries) ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics, arg.OrganizationID, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupTopics = `-- name: LookupTopics :many
SELECT id, organization_id, channel_id, name, is_default, created_at FROM topic
WHERE organization_id = $1 AND channel_id = $2 AND id = ANY($3::uuid[])
`

type LookupTopicsParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	TopicIds       []pgtype.UUID
}

func (q *Queries) LookupTopics(ctx context.Context, arg LookupTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, lookupTopics, arg.OrganizationID, arg.ChannelID, arg.TopicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveMessages = `-- name: MoveMessages :execrows
UPDATE message SET topic_id = $1
WHERE organization_id = $2 AND channel_id = $3
  AND topic_id = $4 AND id = ANY($5::uuid[])
`

type MoveMessagesParams struct {
	ToTopicID      pgtype.UUID
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	FromTopicID    pgtype.UUID
	MessageIds     []pgtype.UUID
}

// Listed exception (feature map): branching writes message.topic_id. Only
// messages still in the expected topic move; the caller compares the count
// with the selection and rolls back on a mismatch (409).
func (q *Queries) MoveMessages(ctx context.Context, arg MoveMessagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveMessages,
		arg.ToTopicID,
		arg.OrganizationID,
		arg.ChannelID,
		arg.FromTopicID,
		arg.MessageIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
