// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	TokenHash []byte
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
