// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session (token_hash, account_id, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	AccountID pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.AccountID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :many
DELETE FROM session WHERE token_hash = $1 RETURNING id
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT session.id AS session_id, session.expires_at, account.id, account.email, account.display_name
FROM session JOIN account ON account.id = session.account_id
WHERE session.token_hash = $1 AND session.expires_at > $2
`

type GetSessionByTokenHashParams struct {
	TokenHash []byte
	Now       pgtype.Timestamptz
}

type GetSessionByTokenHashRow struct {
	SessionID   pgtype.UUID
	ExpiresAt   pgtype.Timestamptz
	ID          pgtype.UUID
	Email       string
	DisplayName string
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash, arg.Now)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.ID,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}
