#!/usr/bin/env bash
# Writes docs/dependencies.md, the package-import edges between this
# module's packages, or with --check fails when that file is stale. It uses
# only `go list`, so it needs no tool beyond Go itself.
set -euo pipefail
cd "$(dirname "$0")/.."
file=docs/dependencies.md

render() {
  local module
  module=$(go list -m)
  cat <<'HEADER'
# Package dependencies

<!-- Generated by `make deps` (scripts/deps.sh) from `go list`. Do not edit. -->

The import edges from this module's packages under `internal/` and `cmd/`
to other packages of this module. They come from non-test Go files only;
test-only imports are left out. They are listed for `GOOS=linux`
`GOARCH=amd64` with cgo enabled, the platform CI builds for, so the list is
the same on every machine. `make check` fails when this file is stale.

A new line here is a new package dependency: say why in the pull request.
This list forbids nothing (depguard enforces the layering rules). It does
not show calls through an edge that already exists, dependencies inside one
package, or SQL access to tables.

```text
HEADER
  # .Imports holds the imports of non-test files only (tests are in
  # .TestImports and .XTestImports). Fixing the platform keeps
  # build-constrained files from changing the list between machines. Cgo
  # stays on, as in CI's default build: with it off, a file importing "C"
  # would be dropped and its edges would silently vanish. Without cgo files
  # go list needs no C compiler.
  GOOS=linux GOARCH=amd64 CGO_ENABLED=1 GOFLAGS= go list \
    -f '{{$p := .ImportPath}}{{range .Imports}}{{$p}} {{.}}{{"\n"}}{{end}}' \
    ./internal/... ./cmd/... |
    awk -v prefix="$module/" '
      index($2, prefix) == 1 {
        print substr($1, length(prefix) + 1) " -> " substr($2, length(prefix) + 1)
      }' |
    LC_ALL=C sort -u
  printf '```\n'
}

case "${1:-}" in
"")
  render >"$file.tmp"
  mv "$file.tmp" "$file"
  ;;
--check)
  if ! diff -u "$file" <(render); then
    printf '\n%s is stale: run `make deps` and commit the result.\n' "$file" >&2
    exit 1
  fi
  ;;
*)
  echo "usage: scripts/deps.sh [--check]" >&2
  exit 2
  ;;
esac
