// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const firstChannelMessageAfter = `-- name: FirstChannelMessageAfter :one
SELECT event_seq FROM message
WHERE organization_id = $1 AND channel_id = $2 AND event_seq > $3
ORDER BY event_seq LIMIT 1
`

type FirstChannelMessageAfterParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	EventSeq       int64
}

func (q *Queries) FirstChannelMessageAfter(ctx context.Context, arg FirstChannelMessageAfterParams) (int64, error) {
	row := q.db.QueryRow(ctx, firstChannelMessageAfter, arg.OrganizationID, arg.ChannelID, arg.EventSeq)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, organization_id, channel_id, member_id, body, event_seq, created_at, topic_id, moved_event_seq FROM message
WHERE organization_id = $1 AND channel_id = $2 AND event_seq = $3
`

type GetMessageParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	EventSeq       int64
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.OrganizationID, arg.ChannelID, arg.EventSeq)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.MemberID,
		&i.Body,
		&i.EventSeq,
		&i.CreatedAt,
		&i.TopicID,
		&i.MovedEventSeq,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, organization_id, channel_id, member_id, body, event_seq, created_at, topic_id, moved_event_seq FROM message
WHERE organization_id = $1 AND channel_id = $2 AND id = ANY($3::uuid[])
ORDER BY event_seq DESC
`

type GetMessagesParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	MessageIds     []pgtype.UUID
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.OrganizationID, arg.ChannelID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelID,
			&i.MemberID,
			&i.Body,
			&i.EventSeq,
			&i.CreatedAt,
			&i.TopicID,
			&i.MovedEventSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO message (organization_id, channel_id, topic_id, member_id, body, event_seq)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, organization_id, channel_id, member_id, body, event_seq, created_at, topic_id, moved_event_seq
`

type InsertMessageParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	TopicID        pgtype.UUID
	MemberID       pgtype.UUID
	Body           string
	EventSeq       int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.OrganizationID,
		arg.ChannelID,
		arg.TopicID,
		arg.MemberID,
		arg.Body,
		arg.EventSeq,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.MemberID,
		&i.Body,
		&i.EventSeq,
		&i.CreatedAt,
		&i.TopicID,
		&i.MovedEventSeq,
	)
	return i, err
}

const lastChannelMessageBefore = `-- name: LastChannelMessageBefore :one
SELECT event_seq FROM message
WHERE organization_id = $1 AND channel_id = $2 AND event_seq < $3
ORDER BY event_seq DESC LIMIT 1
`

type LastChannelMessageBeforeParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	EventSeq       int64
}

func (q *Queries) LastChannelMessageBefore(ctx context.Context, arg LastChannelMessageBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, lastChannelMessageBefore, arg.OrganizationID, arg.ChannelID, arg.EventSeq)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, organization_id, channel_id, member_id, body, event_seq, created_at, topic_id, moved_event_seq FROM message
WHERE organization_id = $1 AND channel_id = $2
  AND ($3::uuid IS NULL OR topic_id = $3::uuid)
  AND ($4::bigint IS NULL OR event_seq < $4::bigint)
ORDER BY event_seq DESC
LIMIT $5
`

type ListMessagesBeforeParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	TopicID        pgtype.UUID
	BeforeEventSeq pgtype.Int8
	Limit          int32
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore,
		arg.OrganizationID,
		arg.ChannelID,
		arg.TopicID,
		arg.BeforeEventSeq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelID,
			&i.MemberID,
			&i.Body,
			&i.EventSeq,
			&i.CreatedAt,
			&i.TopicID,
			&i.MovedEventSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topicUnreadRangeBounds = `-- name: TopicUnreadRangeBounds :many
SELECT coalesce((SELECT p.event_seq + 1 FROM message p
        WHERE p.organization_id = $1 AND p.channel_id = $2
          AND p.event_seq < m.event_seq ORDER BY p.event_seq DESC LIMIT 1), 1)::bigint AS lo,
       coalesce((SELECT n.event_seq FROM message n
        WHERE n.organization_id = $1 AND n.channel_id = $2
          AND n.event_seq > m.event_seq ORDER BY n.event_seq LIMIT 1), m.event_seq + 1)::bigint AS hi
FROM message m
WHERE m.organization_id = $1 AND m.channel_id = $2
  AND m.topic_id = $3
  AND m.event_seq > $4::bigint
  AND (m.event_seq > $5::bigint
       OR (m.event_seq <= $5::bigint AND m.moved_event_seq > $5::bigint))
  AND m.event_seq <= $6::bigint
  AND (m.moved_event_seq IS NULL OR m.moved_event_seq <= $6::bigint)
  AND NOT ($7::int8multirange @> m.event_seq)
ORDER BY m.event_seq
`

type TopicUnreadRangeBoundsParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	TopicID        pgtype.UUID
	PrefixBefore   int64
	Floor          int64
	Cursor         int64
	ReadSet        pgtype.Multirange[pgtype.Range[pgtype.Int8]]
}

type TopicUnreadRangeBoundsRow struct {
	Lo int64
	Hi int64
}

func (q *Queries) TopicUnreadRangeBounds(ctx context.Context, arg TopicUnreadRangeBoundsParams) ([]TopicUnreadRangeBoundsRow, error) {
	rows, err := q.db.Query(ctx, topicUnreadRangeBounds,
		arg.OrganizationID,
		arg.ChannelID,
		arg.TopicID,
		arg.PrefixBefore,
		arg.Floor,
		arg.Cursor,
		arg.ReadSet,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopicUnreadRangeBoundsRow
	for rows.Next() {
		var i TopicUnreadRangeBoundsRow
		if err := rows.Scan(&i.Lo, &i.Hi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
