// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO message (organization_id, channel_id, topic_id, member_id, body, event_seq)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, organization_id, channel_id, member_id, body, event_seq, created_at, topic_id
`

type InsertMessageParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	TopicID        pgtype.UUID
	MemberID       pgtype.UUID
	Body           string
	EventSeq       int64
}

// Duplicates the legacy query in db/queries/message.sql, which step 4.15 deletes.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.OrganizationID,
		arg.ChannelID,
		arg.TopicID,
		arg.MemberID,
		arg.Body,
		arg.EventSeq,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.MemberID,
		&i.Body,
		&i.EventSeq,
		&i.CreatedAt,
		&i.TopicID,
	)
	return i, err
}
