// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTopic = `-- name: GetTopic :one
SELECT id, organization_id, channel_id, name, is_default, created_at FROM topic WHERE organization_id = $1 AND channel_id = $2 AND id = $3
`

type GetTopicParams struct {
	OrganizationID pgtype.UUID
	ChannelID      pgtype.UUID
	ID             pgtype.UUID
}

// Duplicates the legacy query in db/queries/topic.sql, which step 4.16 deletes.
// The organisation and channel predicates are the read's scope check.
func (q *Queries) GetTopic(ctx context.Context, arg GetTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, arg.OrganizationID, arg.ChannelID, arg.ID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
