// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unread.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChannelUnread = `-- name: CountChannelUnread :many
WITH gaps AS (
    SELECT ids.channel_id, los.lo_before, his.hi, ids.n
    FROM unnest($2::uuid[]) WITH ORDINALITY AS ids(channel_id, n)
    JOIN unnest($3::bigint[]) WITH ORDINALITY AS los(lo_before, n) ON los.n = ids.n
    JOIN unnest($4::bigint[]) WITH ORDINALITY AS his(hi, n) ON his.n = ids.n
), bounded AS (
    SELECT c.channel_id, messages.event_seq
    FROM unnest($1::uuid[]) AS c(channel_id)
    CROSS JOIN LATERAL (
        SELECT m.event_seq
        FROM (SELECT lo_before, hi FROM gaps WHERE gaps.channel_id = c.channel_id ORDER BY n) g
        CROSS JOIN LATERAL (
            SELECT event_seq FROM message
            WHERE organization_id = $5
              AND channel_id = c.channel_id
              AND event_seq > g.lo_before AND event_seq < g.hi
            ORDER BY event_seq LIMIT 100
        ) m
        LIMIT 100
    ) messages
)
SELECT c.channel_id::uuid AS channel_id,
    (SELECT count(*) FROM bounded WHERE bounded.channel_id = c.channel_id) AS unread_count,
    coalesce((SELECT event_seq FROM bounded WHERE bounded.channel_id = c.channel_id ORDER BY event_seq LIMIT 1), 0)::bigint AS first_unread
FROM unnest($1::uuid[]) AS c(channel_id)
`

type CountChannelUnreadParams struct {
	ChannelIds     []pgtype.UUID
	GapChannelIds  []pgtype.UUID
	GapLosBefore   []int64
	GapHis         []int64
	OrganizationID pgtype.UUID
}

type CountChannelUnreadRow struct {
	ChannelID   pgtype.UUID
	UnreadCount int64
	FirstUnread int64
}

func (q *Queries) CountChannelUnread(ctx context.Context, arg CountChannelUnreadParams) ([]CountChannelUnreadRow, error) {
	rows, err := q.db.Query(ctx, countChannelUnread,
		arg.ChannelIds,
		arg.GapChannelIds,
		arg.GapLosBefore,
		arg.GapHis,
		arg.OrganizationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChannelUnreadRow
	for rows.Next() {
		var i CountChannelUnreadRow
		if err := rows.Scan(&i.ChannelID, &i.UnreadCount, &i.FirstUnread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
