package domain

// ID identifies a stored entity. Ids are UUIDv7 values generated by
// PostgreSQL, kept as raw bytes so that domain has no database dependency.
type ID [16]byte

// Account is a person who can sign in. It is global, not tied to one
// organisation; its password hash never leaves the persistence layer.
type Account struct {
	ID          ID
	Email       string
	DisplayName string
}
