// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventsAfter = `-- name: EventsAfter :many
SELECT seq, kind, audience_member_id, data FROM event_log
WHERE organization_id = $1 AND seq > $2
ORDER BY seq LIMIT $3::bigint
`

type EventsAfterParams struct {
	OrganizationID pgtype.UUID
	AfterSeq       int64
	BatchLimit     int64
}

type EventsAfterRow struct {
	Seq              int64
	Kind             string
	AudienceMemberID pgtype.UUID
	Data             []byte
}

// The caller reads org's cursor bounds first, in the same snapshot.
func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]EventsAfterRow, error) {
	rows, err := q.db.Query(ctx, eventsAfter, arg.OrganizationID, arg.AfterSeq, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsAfterRow
	for rows.Next() {
		var i EventsAfterRow
		if err := rows.Scan(
			&i.Seq,
			&i.Kind,
			&i.AudienceMemberID,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO event_log (organization_id, seq, kind, audience_member_id, data)
VALUES ($1, $2, $3, $4, $5::jsonb)
`

type InsertEventParams struct {
	OrganizationID   pgtype.UUID
	Seq              int64
	Kind             string
	AudienceMemberID pgtype.UUID
	Data             []byte
}

// The publisher encoded data; realtime stores it without knowing the kind.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.OrganizationID,
		arg.Seq,
		arg.Kind,
		arg.AudienceMemberID,
		arg.Data,
	)
	return err
}
