// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEventsThrough = `-- name: DeleteEventsThrough :one
WITH deleted AS (
    DELETE FROM event_log
    WHERE organization_id = $1 AND seq <= $2::bigint
    RETURNING seq
)
SELECT count(*)::bigint AS deleted, coalesce(max(seq), 0)::bigint AS through FROM deleted
`

type DeleteEventsThroughParams struct {
	OrganizationID pgtype.UUID
	Through        int64
}

type DeleteEventsThroughRow struct {
	Deleted int64
	Through int64
}

func (q *Queries) DeleteEventsThrough(ctx context.Context, arg DeleteEventsThroughParams) (DeleteEventsThroughRow, error) {
	row := q.db.QueryRow(ctx, deleteEventsThrough, arg.OrganizationID, arg.Through)
	var i DeleteEventsThroughRow
	err := row.Scan(&i.Deleted, &i.Through)
	return i, err
}

const eventsAfter = `-- name: EventsAfter :many
SELECT seq, kind, audience_member_id, data FROM event_log
WHERE organization_id = $1 AND seq > $2
ORDER BY seq LIMIT $3::bigint
`

type EventsAfterParams struct {
	OrganizationID pgtype.UUID
	AfterSeq       int64
	BatchLimit     int64
}

type EventsAfterRow struct {
	Seq              int64
	Kind             string
	AudienceMemberID pgtype.UUID
	Data             []byte
}

// The caller reads org's cursor bounds first, in the same snapshot.
func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]EventsAfterRow, error) {
	rows, err := q.db.Query(ctx, eventsAfter, arg.OrganizationID, arg.AfterSeq, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsAfterRow
	for rows.Next() {
		var i EventsAfterRow
		if err := rows.Scan(
			&i.Seq,
			&i.Kind,
			&i.AudienceMemberID,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO event_log (organization_id, seq, kind, audience_member_id, data)
VALUES ($1, $2, $3, $4, $5::jsonb)
`

type InsertEventParams struct {
	OrganizationID   pgtype.UUID
	Seq              int64
	Kind             string
	AudienceMemberID pgtype.UUID
	Data             []byte
}

// The publisher encoded data; realtime stores it without knowing the kind.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.OrganizationID,
		arg.Seq,
		arg.Kind,
		arg.AudienceMemberID,
		arg.Data,
	)
	return err
}

const lowestEvents = `-- name: LowestEvents :many
SELECT seq, created_at FROM event_log
WHERE organization_id = $1
ORDER BY seq LIMIT 1000
`

type LowestEventsRow struct {
	Seq       int64
	CreatedAt pgtype.Timestamptz
}

// The cleaner reads these after taking the organisation lock, so it sees
// committed progress by concurrent cleaners; 1,000 bounds the work under it.
func (q *Queries) LowestEvents(ctx context.Context, organizationID pgtype.UUID) ([]LowestEventsRow, error) {
	rows, err := q.db.Query(ctx, lowestEvents, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LowestEventsRow
	for rows.Next() {
		var i LowestEventsRow
		if err := rows.Scan(&i.Seq, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationsWithExpiredEvents = `-- name: OrganizationsWithExpiredEvents :many
SELECT DISTINCT organization_id FROM event_log WHERE created_at < $1 ORDER BY organization_id
`

func (q *Queries) OrganizationsWithExpiredEvents(ctx context.Context, cutoff pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, organizationsWithExpiredEvents, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var organization_id pgtype.UUID
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
